version: '3'
services:
  backend:
    image: mysql:5.7
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: {DB_USER}
      MYSQL_PASSWORD: {DB_PASSWORD}
      MYSQL_DB: myDb
